### ISSUE TITLE
Add colours to the answers

### ISSUE THREAD

**Issue by KryMucus** [KryMucus/-Quiz_Game---Jules_Deleuse---CDOF3-#1]
I'd like the answers to be green if true, and red if false

**Comment by analytical-aakriti** [comment]
Hey can you assign this to me?

**Comment by KryMucus** [comment]
Hey, I just assigned it to you ! Thanks for the help !

**Comment by KryMucus** [comment]
hey, how is it going  @analytical-aakriti  ?

**Comment by analytical-aakriti** [comment]
here's my PR : https://github.com/KryMucus/-Quiz_Game---Jules_Deleuse---CDOF3-/pull/7

**Comment by KryMucus** [comment]
Thank you for contributing to the project @analytical-aakriti !
