### ISSUE TITLE
Update the READ.ME

### ISSUE THREAD

**Issue by KryMucus** [KryMucus/-Quiz_Game---Jules_Deleuse---CDOF3-#2]
I mistakenly reused a  previous README, i'd like someone to update it.

**Comment by Magnoir** [comment]
Hello, I think I can update your documentation. I will send you a merge request

**Comment by KryMucus** [comment]
> Hello, I think I can update your documentation. I will send you a merge request

Thanks Magnor, I will assign you the issue, don't hesitate to ask me any questions.
