### ISSUE TITLE
Project Name Adjustment and Response Handling Improvement

### ISSUE THREAD

**Issue by Mathious6** [KryMucus/-Quiz_Game---Jules_Deleuse---CDOF3-#3]
I've identified a couple of areas in your quiz project that could benefit from some tweaks to enhance usability and accuracy.

1. **Project Naming Issue:** Currently, the project name begins with a hyphen ('-'), which complicates command-line interactions, resulting in errors like `bash: cd: -Q: invalid option`. To streamline usage and avoid such issues, would you consider renaming the project? A name without leading special characters would be more accessible for users navigating via the command line.

2. **Response Validation Enhancement:** I've noticed that the quiz response validation doesn't account for trailing spaces. For instance, if the correct answer is 'c' but a user accidentally inputs 'c ' (with an extra space), the system marks it as incorrect. To resolve this, I suggest implementing a .strip() method on the response strings. This small change would ensure that unintentional whitespace doesn't impact the accuracy of the answers. Would it be okay for me to add this feature?

These enhancements aim to make the project more user-friendly and error-proof. I'd be happy to implement these changes if you agree they would be beneficial :rocket:

**Comment by KryMucus** [comment]
Hi @Mathious6, these are very good ideas, I'd be really glad if you were to implement them ! Thanks for being so helpful  !! 

have you, perchance, seen my question on the current bug on your repo ?

**Comment by Mathious6** [comment]
> Hi @Mathious6, these are very good ideas, I'd be really glad if you were to implement them ! Thanks for being so helpful !!
> 
> have you, perchance, seen my question on the current bug on your repo ?

Hi @KryMucus , thanks for your positive response and for welcoming my suggestions! I'm excited to implement these improvements on your project.

Regarding your question on my repo, yes, I have seen it and already provided a response. If there's anything else you need or further clarification required, feel free to let me know. Happy to help out!
